apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default  # Hoặc namespace mà bạn triển khai Deployment
  name: zeppelin-deployment-manager
rules:
- apiGroups: ["apps"]    # API group cho Deployment
  resources: ["deployments"]
  verbs: ["create", "get", "list", "watch", "update"]
- apiGroups: [""]    # API group mặc định
  resources: ["pods", "pods/log", "services","persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "create"]

