apiVersion: apps/v1
kind: Deployment
metadata:
  name: zeppelin
  labels:
    app: zeppelin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zeppelin
  template:
    metadata:
      labels:
        app: zeppelin
    spec:
      serviceAccountName: zeppelin-sa 
      containers:
      - name: zeppelin
        image: localhost:5000/apache/zeppelin:0.10.0
        env:
          - name: SPARK_HOME
            value: "/opt/spark"
          - name: SPARK_MASTER
            value: "spark://spark-master:7077"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: zeppelin-storage
          mountPath: /zeppelin
      volumes:
      - name: zeppelin-storage
        persistentVolumeClaim:
          claimName: zeppelin-pvc
