apiVersion: v1
kind: Service
metadata:
  name: zeppelin-service
spec:
  type: NodePort  # Bạn có thể thay bằng NodePort hoặc LoadBalancer tùy yêu cầu
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30037
  selector:
    app: zeppelin
