apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
  namespace: cattle-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: base-demo
  template:
    metadata:
      labels:
        app: base-demo
    spec:
      serviceAccountName: my-service-account
      containers:
      - name: base-demo-app
        image: duongthanh/base-demo:v1
        imagePullPolicy: Always 
        securityContext:
         runAsUser: 0
        volumeMounts:
        - mountPath: /app/scripts
          name: config-volume-delete
        ports:
        - containerPort: 8080
        env:
          - name: SPRING_PROFILES_ACTIVE
            valueFrom:
              configMapKeyRef:
               name: spring-boot-config
               key: SPRING_PROFILES_ACTIVE
        envFrom:
          - configMapRef:
             name: spring-boot-config
      volumes:
        - name: config-volume-delete
          configMap:
           name: delete-validate-rancher
           defaultMode: 0777  
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-service
  namespace: cattle-system
spec:
  selector:
    app: base-demo    
  ports:
    - protocol: TCP
      port: 8080        
      targetPort: 8080   
      nodePort: 30037    
  type: NodePort         
