apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-service-account
  namespace: cattle-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-service-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list", "delete"]
  - apiGroups: [ "admissionregistration.k8s.io" ]
    resources: [ "validatingwebhookconfigurations", "mutatingwebhookconfigurations" ]
    verbs: [ "get", "list", "delete" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: my-service-account-binding
subjects:
  - kind: ServiceAccount
    name: my-service-account
    namespace: cattle-system
roleRef:
  kind: ClusterRole
  name: cluster-service-role
  apiGroup: rbac.authorization.k8s.io