apiVersion: v1
kind: Service
metadata:
  name: oracle-service
spec:
  selector:
    app: oracle-db
  ports:
  - name: oracle
    protocol: TCP
    port: 1521
    targetPort: 1521
  - name: oem
    protocol: TCP
    port: 5500
    targetPort: 5500
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oracle-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oracle-db
  template:
    metadata:
      labels:
        app: oracle-db
    spec:
      containers:
      - name: oracle
        image: container-registry.oracle.com/database/enterprise:21.3.0.0 # Thay đổi phiên bản nếu cần
        ports:
        - containerPort: 1521 # Cổng Oracle Database
        - containerPort: 5500 # Cổng Enterprise Manager (nếu cần)
        env:
        - name: ORACLE_SID
          value: "ORCLCDB" # Tên SID mặc định
        - name: ORACLE_PDB
          value: "ORCLPDB1" # Tên Pluggable Database mặc định
        - name: ORACLE_PWD
          value: "123456" # Đặt mật khẩu mạnh
        volumeMounts:
        - name: oracle-storage
          mountPath: /u01/app/oracle
      volumes:
      - name: oracle-storage
        persistentVolumeClaim:
          claimName: oracle-pvc
